file_status = {
    'UPLOAD_SUCCESS': 'UPLOAD_SUCCESS',
    'UPLOAD_FAILED': 'UPLOAD_FAILED',
    'VALIDATION_SUCCESS': 'VALIDATION_SUCCESS',
    'VALIDATION_FAILED': 'VALIDATION_FAILED',
    'INGESTION_SUCCESS': 'INGESTION_SUCCESS',
    'INGESTION_FAILED': 'INGESTION_FAILED',
    'LOAD_SUCCESS': 'LOAD_SUCCESS',
    'LOAD_FAILED': 'LOAD_FAILED'
}